// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GiveLifeAPI.Models
{
    public partial class Cases
    {
        public Cases()
        {
            Cupon = new HashSet<Cupon>();
            Post = new HashSet<Post>();
        }

        [StringLength(50)]
        public string Name { get; set; }
        [Key]
        [Column("NationalID")]
        [StringLength(14)]
        public string NationalId { get; set; }
        [Column("Family_Member_Num")]
        public int? FamilyMemberNum { get; set; }
        [Column("Child_Num")]
        public int? ChildNum { get; set; }
        [Column("RegionID")]
        public int RegionId { get; set; }
        [StringLength(15)]
        public string Status { get; set; }
        public bool Deleted { get; set; }
        
        [ForeignKey("RegionId")]
        [InverseProperty("Cases")]
        public virtual Region Region { get; set; }
        [InverseProperty("CaseNational")]
        public virtual ICollection<Cupon> Cupon { get; set; }
        [InverseProperty("Case")]
        public virtual ICollection<Post> Post { get; set; }
    }
}