// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GiveLifeAPI.Models
{
    public partial class Cupon
    {
        [Column("CuponID")]
        public int CuponId { get; set; }
        [StringLength(50)]
        public string CuponIdentity { get; set; }
        public decimal AmountOfMoney { get; set; }
        [StringLength(50)]
        public NeedCatogry ProductCategory { get; set; }
        public DateTime? ExpireDate { get; set; }
        [Required]
        [Column("CaseNationalID")]
        [StringLength(14)]
        public string CaseNationalId { get; set; }
        [Column("CoordID")]
        public int? CoordId { get; set; }
        [Column("RegionID")]
        public int RegionId { get; set; }
        public bool Deleted { get; set; }

        [ForeignKey("CaseNationalId")]
        [InverseProperty("Cupon")]
        public virtual Cases CaseNational { get; set; }
        [ForeignKey("CoordId")]
        [InverseProperty("Cupon")]
        public virtual RegionCoordinator Coord { get; set; }
        [ForeignKey("RegionId")]
        [InverseProperty("Cupon")]
        public virtual Region Region { get; set; }
    }
}