// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GiveLifeAPI.Models
{
    public partial class Group
    {
        public Group()
        {
            UserGroup = new HashSet<UserGroup>();
        }

        [Column("GroupID")]
        public int GroupId { get; set; }
        [Required]
        [StringLength(50)]
        public string GroupName { get; set; }
        public bool Deleted { get; set; }

        [InverseProperty("Group")]
        public virtual ICollection<UserGroup> UserGroup { get; set; }
    }
}