// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GiveLifeAPI.Models
{
    public partial class OnlineDonner
    {
        [Key]
        [Column("DonnerID")]
        public int DonnerId { get; set; }
        public int? WalletBalance { get; set; }
        [Required]
        [StringLength(8)]
        public string Password { get; set; }
        [StringLength(16)]
        public string VisaNum { get; set; }
        public bool Deleted { get; set; }
    }
}