// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GiveLifeAPI.Models
{
    public partial class Organization
    {
        public Organization()
        {
            Post = new HashSet<Post>();
        }

        [Key]
        [Column("OrganizationID")]
        public int OrganizationId { get; set; }
        [Required]
        [StringLength(50)]
        public string OrgName { get; set; }
        [Required]
        [StringLength(50)]
        public string ActiveType { get; set; }
        [Column(TypeName = "money")]
        public decimal? WalletBalance { get; set; }
        [StringLength(16)]
        public string VisaNum { get; set; }
        [Required]
        [StringLength(50)]
        public string Category { get; set; }
        [Column("RegionID")]
        public int RegionId { get; set; }
        public bool Deleted { get; set; }

        [ForeignKey("RegionId")]
        [InverseProperty("Organization")]
        public virtual Region Region { get; set; }
        [InverseProperty("Org")]
        public virtual ICollection<Post> Post { get; set; }
    }
}