// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GiveLifeAPI.Models
{
    public partial class RegionAdmin
    {
        public RegionAdmin()
        {
            RegionCoordinator = new HashSet<RegionCoordinator>();
        }

        [Key]
        [Column("AdminID")]
        public int AdminId { get; set; }
        [Column("RegionID")]
        public int? RegionId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Column(TypeName = "money")]
        public decimal BankAccountBalance { get; set; }
        [Required]
        [StringLength(8)]
        public string Password { get; set; }
        public bool Deleted { get; set; }

        [ForeignKey("RegionId")]
        [InverseProperty("RegionAdmin")]
        public virtual Region Region { get; set; }
        [InverseProperty("RegionAdmin")]
        public virtual ICollection<RegionCoordinator> RegionCoordinator { get; set; }
    }
}