// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GiveLifeAPI.Models
{
    public partial class Region
    {
        public Region()
        {
            Cases = new HashSet<Cases>();
            Cupon = new HashSet<Cupon>();
            Organization = new HashSet<Organization>();
            Post = new HashSet<Post>();
            RegionAdmin = new HashSet<RegionAdmin>();
            RegionCoordinator = new HashSet<RegionCoordinator>();
        }

        public int RegionId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        public bool Deleted { get; set; }

        [InverseProperty("Region")]
        public virtual ICollection<Cases> Cases { get; set; }
        [InverseProperty("Region")]
        public virtual ICollection<Cupon> Cupon { get; set; }
        [InverseProperty("Region")]
        public virtual ICollection<Organization> Organization { get; set; }
        [InverseProperty("Region")]
        public virtual ICollection<Post> Post { get; set; }
        [InverseProperty("Region")]
        public virtual ICollection<RegionAdmin> RegionAdmin { get; set; }
        [InverseProperty("Region")]
        public virtual ICollection<RegionCoordinator> RegionCoordinator { get; set; }
    }
}