// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GiveLifeAPI.Models
{
    [Table("User_Group")]
    public partial class UserGroup
    {
        [Column("UserID")]
        public int UserId { get; set; }
        [Column("GroupID")]
        public int GroupId { get; set; }
        public bool Deleted { get; set; }

        [ForeignKey("GroupId")]
        [InverseProperty("UserGroup")]
        public virtual Group Group { get; set; }
        [ForeignKey("UserId")]
        [InverseProperty("UserGroup")]
        public virtual User User { get; set; }
    }
}